name: SRE Summer Camp's talk proposal
description: Submit a talk for the SRE Summer Camp
labels: [sre-summercamp]
body:
- type: input
  attributes:
    label: Author's Name
    description: Your preferred name, it can be your Twitter handle too.
  validations:
    required: true
- type: textarea
  attributes:
    label: Author's Bio
    description: A few words about you.
  validations:
    required: false
- type: dropdown
  attributes:
    label: Expected time
    options:
      - Standard talk (~40 min)
      - Short talk (~15 min)
  validations:
    required: true
- type: checkboxes
  attributes:
    label: Language
    description: Most of the audience are French speakers but they understand English too. 
    options:
      - label: "French"
      - label: "English"
- type: textarea
  attributes:
    label: Abstract
    description: Describe your talk in a few lines.
  validations:
    required: true
